# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '\u677f\u5757', 'verbose_name_plural': '\u677f\u5757'},
        ),
        migrations.AlterField(
            model_name='block',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='\u677f\u5757\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='block',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u677f\u5757\u540d\u79f0'),
        ),
    ]
