# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='\u5efa\u8bbe\u8005')),
                ('userExpTime', models.IntegerField(verbose_name='\u5efa\u8bbe\u65f6\u95f4')),
                ('userSex', models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], verbose_name='\u6027\u522b')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
    ]
